### ISSUE TITLE
:art: 홈 - 접근성 개선

### ISSUE THREAD

**Issue by KimHayeon1** [yonainthefish/MOMOO-React#260]
### Description
- 앨범 수정 모달 - 체크 아이콘 -> 저장(텍스트)
- 홈 - 앨범 - 더보기 버튼 영역 키우기 (9mm 이상)
- 입력해주세요 → 입력해 주세요 (맞춤법)

### To-do
- [x] 앨범 수정 모달 - 체크 아이콘 -> 저장(텍스트)
- [x] 홈 - 앨범 - 더보기 버튼 영역 키우기
- [x] 입력해주세요 → 입력해 주세요

### ETC
![image](https://github.com/yonainthefish/MoMoo/assets/108985221/f532c5f3-3833-4013-87db-263e54cc8479)
<img src='https://github.com/yonainthefish/MoMoo/assets/108985221/4f7fd012-df81-47ea-b0af-04547143a96d' width='300px'>
![image](https://github.com/yonainthefish/MoMoo/assets/126536402/f5a3bd04-7f50-4529-a71a-13910ac73ac0)
